In [1]:
import pandas as pd

# Load dataset
df = pd.read_csv("student_dataset.csv")

# View first rows
df.head()

,student_id,first_name,last_name,major,gpa,grad_year,credits_completed,enrolled_courses,email,phone,residence_hall,scholarship,club,advisor,holds
0,101,George,Smith,History,2.68,2026,118,3,student101@college.edu,555-0101,Maple,False,Sports,Dr. Patel,NaN
1,102,Tina,Jones,CS,2.75,2026,74,3,student102@college.edu,555-0102,Cedar,True,Math,Dr. Chen,Academic
2,103,Oliver,White,Math,2.19,2024,33,3,student103@college.edu,555-0103,Cedar,False,Music,Dr. Chen,Financial
3,104,Kevin,Miller,CS,3.16,2023,65,4,student104@college.edu,555-0104,Cedar,False,Debate,Dr. Chen,NaN
4,105,Hannah,Wilson,History,2.07,2025,99,3,student105@college.edu,555-0105,Maple,False,Music,Dr. Chen,NaN

In [2]:
df.info()
df.describe()
df.sample(5)

<class 'pandas.DataFrame'>
RangeIndex: 110 entries, 0 to 109
Data columns (total 15 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   student_id         110 non-null    int64
 1   first_name         110 non-null    str
 2   last_name          110 non-null    str
 3   major              110 non-null    str
 4   gpa                110 non-null    float64
 5   grad_year          110 non-null    int64
 6   credits_completed  110 non-null    int64
 7   enrolled_courses   110 non-null    int64
 8   email              110 non-null    str
 9   phone              110 non-null    str
 10  residence_hall     110 non-null    str
 11  scholarship        110 non-null    bool
 12  club               110 non-null    str
 13  advisor            110 non-null    str
 14  holds              73 non-null     str
dtypes: bool(1), float64(1), int64(4), str(9)
memory usage: 12.3 KB

,student_id,first_name,last_name,major,gpa,grad_year,credits_completed,enrolled_courses,email,phone,residence_hall,scholarship,club,advisor,holds
105,206,Charlie,Williams,Business,2.56,2024,92,6,student206@college.edu,555-0206,Pine,False,Sports,Dr. Chen,Academic
100,201,Charlie,Davis,Business,3.39,2025,47,4,student201@college.edu,555-0201,Pine,False,Sports,Dr. Patel,NaN
62,163,Paula,Johnson,Business,2.87,2023,45,5,student163@college.edu,555-0163,Pine,True,Sports,Dr. Patel,Financial
37,138,Ian,Williams,Biology,2.31,2023,90,4,student138@college.edu,555-0138,Oak,False,Music,Dr. Adams,Financial
3,104,Kevin,Miller,CS,3.16,2023,65,4,student104@college.edu,555-0104,Cedar,False,Debate,Dr. Chen,NaN

In [3]:
df_idx = df.set_index("student_id")
df_idx.head()

,first_name,last_name,major,gpa,grad_year,credits_completed,enrolled_courses,email,phone,residence_hall,scholarship,club,advisor,holds
student_id,,,,,,,,,,,,,,
101,George,Smith,History,2.68,2026,118,3,student101@college.edu,555-0101,Maple,False,Sports,Dr. Patel,NaN
102,Tina,Jones,CS,2.75,2026,74,3,student102@college.edu,555-0102,Cedar,True,Math,Dr. Chen,Academic
103,Oliver,White,Math,2.19,2024,33,3,student103@college.edu,555-0103,Cedar,False,Music,Dr. Chen,Financial
104,Kevin,Miller,CS,3.16,2023,65,4,student104@college.edu,555-0104,Cedar,False,Debate,Dr. Chen,NaN
105,Hannah,Wilson,History,2.07,2025,99,3,student105@college.edu,555-0105,Maple,False,Music,Dr. Chen,NaN

In [4]:
df_idx.loc[105]

first_name                           Hannah
last_name                            Wilson
major                               History
gpa                                    2.07
grad_year                              2025
credits_completed                        99
enrolled_courses                          3
email                student105@college.edu
phone                              555-0105
residence_hall                        Maple
scholarship                           False
club                                  Music
advisor                            Dr. Chen
holds                                   NaN
Name: 105, dtype: object

In [5]:
df_reset = df_idx.reset_index()
df_reset.head()

,student_id,first_name,last_name,major,gpa,grad_year,credits_completed,enrolled_courses,email,phone,residence_hall,scholarship,club,advisor,holds
0,101,George,Smith,History,2.68,2026,118,3,student101@college.edu,555-0101,Maple,False,Sports,Dr. Patel,NaN
1,102,Tina,Jones,CS,2.75,2026,74,3,student102@college.edu,555-0102,Cedar,True,Math,Dr. Chen,Academic
2,103,Oliver,White,Math,2.19,2024,33,3,student103@college.edu,555-0103,Cedar,False,Music,Dr. Chen,Financial
3,104,Kevin,Miller,CS,3.16,2023,65,4,student104@college.edu,555-0104,Cedar,False,Debate,Dr. Chen,NaN
4,105,Hannah,Wilson,History,2.07,2025,99,3,student105@college.edu,555-0105,Maple,False,Music,Dr. Chen,NaN

In [6]:
df_multi = df.set_index(["major", "grad_year"])
df_multi = df_multi.sort_index()
df_multi.head()

                   student_id first_name last_name   gpa  credits_completed  \
major   grad_year
Biology 2023              111     Hannah    Miller  2.07                103
        2023              113        Bob     Perez  2.72                 48
        2023              117      Alice   Jackson  2.43                 42
        2023              121      Julia   Jackson  3.06                 90
        2023              138        Ian  Williams  2.31                 90

                   enrolled_courses                   email     phone  \
major   grad_year
Biology 2023                      5  student111@college.edu  555-0111
        2023                      6  student113@college.edu  555-0113
        2023                      3  student117@college.edu  555-0117
        2023                      5  student121@college.edu  555-0121
        2023                      4  student138@college.edu  555-0138

                  residence_hall  scholarship    club    advisor      holds
major   grad_year
Biology 2023                 Oak         True    Math    Dr. Lee  Financial
        2023                Pine        False  Debate   Dr. Chen        NaN
        2023                Pine         True  Debate  Dr. Patel        NaN
        2023               Cedar        False  Sports   Dr. Chen   Academic
        2023                 Oak        False   Music  Dr. Adams  Financial

In [7]:
df_multi.loc[("CS", 2025)]

                 student_id first_name last_name   gpa  credits_completed  \
major grad_year
CS    2025              118      Laura    Harris  3.25                 87
      2025              139        Bob    Miller  2.50                 76
      2025              159        Bob     Jones  2.20                 86
      2025              167     Hannah     Smith  2.09                 57
      2025              178        Ian   Johnson  3.88                 56

                 enrolled_courses                   email     phone  \
major grad_year
CS    2025                      4  student118@college.edu  555-0118
      2025                      3  student139@college.edu  555-0139
      2025                      6  student159@college.edu  555-0159
      2025                      5  student167@college.edu  555-0167
      2025                      4  student178@college.edu  555-0178

                residence_hall  scholarship      club    advisor      holds
major grad_year
CS    2025               Maple         True  Robotics  Dr. Patel        NaN
      2025               Maple         True      Math  Dr. Adams   Academic
      2025               Maple         True    Debate  Dr. Patel  Financial
      2025                Pine        False    Debate  Dr. Patel  Financial
      2025                 Oak         True    Debate   Dr. Chen  Financial

In [13]:
some_id = df["student_id"].iloc[0]

In [14]:
%%timeit
df[df["student_id"] == some_id]

477 μs ± 202 μs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)

In [10]:
%%timeit
df_idx.loc[some_id]

67.2 μs ± 3.77 μs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)

In this lab, I observed that using an indexed lookup with `.loc[]` was noticeably faster than using Boolean filtering, especially when retrieving a specific student by ID. The Boolean filter had to scan the entire column to find a match, while the indexed lookup accessed the row directly, which makes it more efficient as the dataset grows. I also learned that resetting an index is helpful when I need the indexed column back as a regular column for merging, exporting, or performing other operations that don’t require optimized lookups. Overall, this lab helped me understand how Pandas indexing is similar to SQL indexes, since both improve query performance by organizing data for faster retrieval, and how these same ideas apply to larger distributed systems where efficient data access is critical for handling massive datasets.